# Mise config
# ===========

[settings]
# Detect node version from .nvmrc
idiomatic_version_file_enable_tools = ["node", "python"]

# For the love of god please don't compile Node and Python from source
node.compile = false
python.compile = false

[tools]

# Dotfile management
# ------------------

"cargo:tuckr" = "latest"

# Teaching
# --------

"pipx:markten" = "latest"
"pipx:slides-xp" = "latest"

# COMP1531
# --------

node = "24"
"npm:tsx" = "latest"
# DCC (COMP1511 compiler)
"github:COMP1511UNSW/dcc" = { version = "latest", asset_pattern = "dcc" }

# COMP2511
# --------

gradle = "9.2.0"
java = "21"

# Python
# ------

"pipx:comp1010" = "latest"
poetry = "latest"
uv = "latest"
python = "latest"

# Rust
# ----

# Add WASM target
rust = { version = "latest", targets="x86_64-unknown-linux-gnu,wasm32-unknown-unknown" }
"cargo:bacon" = "latest"

# JavaScript
# ----------

# The eternal struggle to decide between Deno and Bun
bun = "latest"
deno = "latest"

# And PNPM, which is worse, but potentially useful when I want it to be
# NPM-alike
pnpm = "latest"

# Docker
# ------

# Debug Docker builds
"github:ktock/buildg" = "latest"

# Writing
# -------

typst = "latest"

# CLI tools
# ---------

"github:boyter/scc" = "latest"
"pipx:transdoc" = "latest"
"github:Slackadays/Clipboard" = "latest"
"pipx:concussion" = "latest"
"pipx:tldr" = { version = "latest", uvx_args = "--with pip-system-certs" }

# Others
# ------

"pipx:git+https://github.com/MaddyGuthridge/pyqtprotractor.git" = "master"
